In [1]:
# Scenario: AI System for Detecting Lung Diseases from Chest X-rays
# 🚨 The Problem

# A large hospital receives thousands of chest X-rays daily.

# Radiologists are:

# Overworked

# Limited in number

# Required to make fast decisions

# Sometimes critical conditions like:

# 👉 Pneumonia
# 👉 COVID-19
# 👉 Normal lungs

# must be identified within minutes.

# Delays can cost lives.

# 💡 The Solution: Build an AI Assistant

# The hospital decides to deploy an AI model that can pre-screen X-rays and
# alert doctors.

# But there is a challenge…

# ❗ Medical datasets are usually SMALL.

# Training a deep neural network from scratch would require:

# Millions of labeled X-rays

# Massive GPU clusters

# Months of training

# Not practical.

# ⭐ Enter Transfer Learning (Your Code)

# Instead of starting from zero, engineers use:

# 👉 ResNet50 trained on ImageNet

# Although ImageNet contains everyday objects (dogs, cars, etc.),
# the early CNN layers learn universal visual patterns, like:

# ✅ Edges
# ✅ Gradients
# ✅ Textures
# ✅ Shapes

# These features are also present in medical scans.

# Import PyTorch library (main deep learning framework)
import torch

# Import torchvision models (contains pre-trained CNN architectures)
import torchvision.models as models

# Import neural network module from PyTorch
from torch import nn


# -------------------------------------------------------
# Step 1: Load a Pre-trained ResNet50 Model
# -------------------------------------------------------

# ResNet50 is a deep convolutional neural network with 50 layers.
# It is already trained on the ImageNet dataset (1.2 million images, 1000 classes).
# Using a pre-trained model allows us to reuse learned visual features
# such as edges, textures, shapes, and patterns.

model = models.resnet50(pretrained=True)


# -------------------------------------------------------
# Step 2: Freeze All Pre-trained Layers
# -------------------------------------------------------

# Transfer learning strategy:
# We freeze earlier layers so their weights do not change during training.
# These layers already learned general image features.

for param in model.parameters():
    param.requires_grad = False

# requires_grad = False means:
# - Gradients will NOT be computed
# - Weights will NOT be updated during backpropagation
# - Training becomes faster and needs less data


# -------------------------------------------------------
# Step 3: Modify the Final Classification Layer
# -------------------------------------------------------

# The original ResNet50 final layer predicts 1000 classes (ImageNet).
# Our problem only has 3 classes:
# 1. Normal
# 2. Pneumonia
# 3. COVID-19

num_classes = 3

# Replace the last fully connected layer (fc)
# model.fc.in_features gives the number of input features to the layer
# (2048 for ResNet50)

model.fc = nn.Linear(model.fc.in_features, num_classes)

# Now the model output will be 3 neurons instead of 1000.


# -------------------------------------------------------
# Step 4: Train Only the New Layer
# -------------------------------------------------------

# Since earlier layers are frozen,
# only the new fully connected layer will be trained.

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable params: {trainable_params}")

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 113MB/s]

Trainable params: 6147

In [6]:
# Scenario: AI System for Detecting Fraud in Financial Transactions
# 🚨 The Problem
# A major bank processes millions of transactions daily.
# Fraud analysts are:
# - Overwhelmed by the sheer volume
# - Limited in number
# - Required to make instant decisions
# - Missing subtle fraud patterns hidden in massive datasets
# Critical cases like:
# 👉 Credit card fraud
# 👉 Money laundering
# 👉 Normal transactions
# must be flagged in real-time.
# Delays can cost millions and damage customer trust.

# 💡 The Solution: Build an AI Assistant
# The bank deploys an AI model that can pre-screen transactions and alert analysts.
# But here’s the challenge…
# ❗ Fraud datasets are usually imbalanced and small.
# Training a deep neural network from scratch would require:
# - Billions of labeled transactions
# - Huge compute clusters
# - Months of training
# Not practical.

# ⭐ Enter Transfer Learning (Your Code)
# Instead of starting from zero, engineers use:
# 👉 BERT (Bidirectional Encoder Representations from Transformers) trained on massive text corpora.
# Although BERT was trained on general language (Wikipedia, books, etc.), its early layers learn universal text patterns, like:
# - ✅ Word embeddings
# - ✅ Sentence structures
# - ✅ Semantic relationships
# - ✅ Contextual meaning
# These features are also present in transaction descriptions, merchant details, and customer behavior logs.
# By fine-tuning BERT on the bank’s fraud dataset, the AI can quickly learn to distinguish:
# - Suspicious vs. normal transactions
# - Fraud rings vs. genuine customer activity

# ⚡ Just like ResNet50 helps radiologists with X-rays, BERT helps fraud analysts with transaction logs —
# both leveraging transfer learning to solve problems where data is scarce but decisions are critical.

# Import PyTorch (deep learning framework)
import torch

# Import HuggingFace transformers (pre-trained NLP models)
from transformers import BertTokenizer, BertForSequenceClassification

# Import neural network module
from torch import nn


# Step 1: Load Pre-trained BERT Model

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3   # 0 = Normal, 1 = Fraud
)

# Load tokenizer (converts text → tokens for BERT)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')



# Step 2: Freeze BERT Base Layers

for param in model.bert.parameters():
    param.requires_grad = False


# Step 3: Check Trainable Parameters


trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable params: {trainable_params}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Trainable params: 2307

In [16]:
#  The Solution: Build an AI Assistant
# The university deploys an AI model that can pre-screen essays and alert professors about suspicious content.
# But here’s the challenge…
# ❗ Academic plagiarism datasets are usually small and domain-specific.
# Training a deep NLP model from scratch would require:
# - Millions of labeled essays
# - Huge compute resources
# - Months of training
# Not practical.

# ⭐ Enter Transfer Learning (Your Code)
# Instead of starting from zero, engineers use:
# 👉 GPT-style language models trained on massive text corpora (books, articles, Wikipedia).
# Although these corpora contain general language, the early layers learn universal text features, like:
# - ✅ Grammar patterns
# - ✅ Semantic meaning
# - ✅ Sentence structures
# - ✅ Contextual relationships
# These features are also present in student essays.
# By fine-tuning the model on a smaller plagiarism dataset, the AI can quickly learn to distinguish:
# - Original vs. copied content
# - Paraphrased vs. genuinely written text
# - Citation misuse vs. proper referencing

# ⚡ Just like ResNet50 helps radiologists with X-rays, and BERT helps fraud analysts with transactions, GPT-style models help
# educators with essays — all leveraging transfer learning to solve problems where data is scarce but accuracy is critical.


# Import PyTorch (deep learning framework)
import torch

# Import HuggingFace transformers (GPT-style models)
from transformers import GPT2Tokenizer, GPT2ForSequenceClassification

# Import neural network module
from torch import nn


# Step 1: Load Pre-trained GPT Model


model = GPT2ForSequenceClassification.from_pretrained(
    'gpt2',
    num_labels=3   # 0 = Original, 1 = Plagiarized
)

# Load tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')


# Step 2: Freeze GPT Base Layers

for param in model.transformer.parameters():
    param.requires_grad = False

# Only classification head will be trained

# Step 3: Check Trainable Parameters

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable params: {trainable_params}")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key                  | Status     |
---------------------+------------+-
h.{0...11}.attn.bias | UNEXPECTED |
score.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Trainable params: 2304

In [17]:
# Install required libraries if not already installed:
# pip install transformers datasets peft accelerate

# Install required libraries if not already installed:
# pip install transformers datasets peft accelerate

from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
from datasets import Dataset
from peft import get_peft_model, LoraConfig

# 1. Load base model and tokenizer
model_name = "gpt2"   # you can replace with another causal LM
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Ensure pad token exists (GPT-2 doesn't have one by default)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# 2. Define LoRA configuration
lora_config = LoraConfig(
    r=8,                  # rank of low-rank matrices
    lora_alpha=32,        # scaling factor
    lora_dropout=0.1,     # dropout for regularization
    bias="none",          # no bias terms updated
    task_type="CAUSAL_LM",# language modeling task
    target_modules=["c_attn"]  # GPT-2 attention projection layers
)

# Wrap model with LoRA adapters
model = get_peft_model(model, lora_config)

# 3. Create a tiny synthetic dataset
train_texts = ["Hello world", "LoRA fine-tuning is fun", "Transformers are powerful"]
eval_texts = ["Testing evaluation", "Another sample"]

train_dataset = Dataset.from_dict({"text": train_texts})
eval_dataset = Dataset.from_dict({"text": eval_texts})

# Tokenization function with labels
def tokenize_function(examples):
    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )
    tokens["labels"] = tokens["input_ids"].copy()  # labels required for loss
    return tokens

# Apply tokenization
train_dataset = train_dataset.map(tokenize_function, batched=True)
eval_dataset = eval_dataset.map(tokenize_function, batched=True)

# Set format for PyTorch
train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
eval_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

# 4. Training configuration
training_args = TrainingArguments(
    output_dir="./lora-finetuned-model",   # save directory
    per_device_train_batch_size=2,         # small batch size
    gradient_accumulation_steps=2,         # accumulate gradients
    learning_rate=2e-4,                    # tuned for LoRA
    num_train_epochs=1,                    # demo run
    logging_steps=1,                       # log every step
    save_strategy="epoch",                 # save at end of epoch
    fp16=True                              # mixed precision training
)

# 5. Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset
)

# 6. Train
trainer.train()

# 7. Save only LoRA adapter weights (few MB instead of GBs!)
model.save_pretrained("./lora-weights")

print("Training complete. LoRA weights saved in ./lora-weights")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Training complete. LoRA weights saved in ./lora-weights

In [23]:
# Scenario: Fraud Detection in Customer Support Chats
# - Problem: Fraudsters often contact bank support pretending to be customers, trying to reset passwords or gain access.
# - Challenge: Analysts can’t manually read millions of chat transcripts.
# - Solution: Use LoRA fine‑tuning on a pretrained language model (like distilbert-base-uncased) to classify chats as:
# - 0 → Normal inquiry
# - 1 → Fraud attempt
# - 2 → Suspicious but unclear


import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from datasets import Dataset
from peft import LoraConfig, get_peft_model, TaskType

model_name = "distilbert-base-uncased"

model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)
tokenizer = AutoTokenizer.from_pretrained(model_name)

lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_CLS,
    target_modules=["q_lin","v_lin"]
)

model = get_peft_model(model, lora_config)

train_texts = [
    "I forgot my password please reset it",
    "Can you reset the account immediately I lost access",
    "Hi I want to check my balance",
    "Please update my email and password quickly",
    "I want to open a new savings account",
    "My account is locked help me login"
]

train_labels = [0,2,0,1,0,2]

eval_texts = [
    "Reset my password now",
    "How to check account balance"
]

eval_labels = [1,0]

train_dataset = Dataset.from_dict({"text": train_texts, "label": train_labels})
eval_dataset = Dataset.from_dict({"text": eval_texts, "label": eval_labels})

def tokenize_function(examples):
    tokens = tokenizer(examples["text"], padding="max_length", truncation=True, max_length=64)
    tokens["labels"] = examples["label"]
    return tokens

train_dataset = train_dataset.map(tokenize_function, batched=True)
eval_dataset = eval_dataset.map(tokenize_function, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids","attention_mask","labels"])
eval_dataset.set_format(type="torch", columns=["input_ids","attention_mask","labels"])

training_args = TrainingArguments(
    output_dir="./fraud-lora-model",
    per_device_train_batch_size=2,
    num_train_epochs=1,
    learning_rate=2e-4,
    logging_steps=1,
    save_strategy="epoch"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset
)

trainer.train()

model.save_pretrained("./fraud-lora-weights")
print("Training complete. LoRA weights saved in ./lora-weights")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/6 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Training complete. LoRA weights saved in ./lora-weights